server:
  port: 8000
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: post-service
  cloud:
    config:
      enabled: false
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/datt_demo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: D@y0989510517
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#app:
#  auth:
#    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
#    tokenExpirationMsec: 864000000
#  cors:
#    allowedOrigins: http://localhost:3000,http://localhost:8765